### ISSUE TITLE
can't install node-ffi on linux/aarch64 platform

### ISSUE THREAD

**Issue by mpo22** [mpo22/node-ffi#1]
on node-ffi master branch

root@avcast-odroidc2:/opt/AVCast/node-ffi.mpo22# uname -a
Linux avcast-odroidc2 3.14.79+ #1 SMP PREEMPT Fri Oct 21 12:07:47 CEST 2016 aarch64 GNU/Linux

detailed compilation log

node-gyp rebuild --verbose
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/nodejs', '/usr/bin/node-gyp', 'rebuild', '--verbose' ]
gyp info using node-gyp@3.4.0
gyp info using node@4.6.1 | linux | arm64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.12+\n"
gyp verb get node dir no --target version specified, falling back to host node version: 4.6.1
gyp verb build dir attempting to create "build" dir: /opt/AVCast/ffi/node_modules/ffi/build
gyp verb build dir "build" dir needed to be created? /opt/AVCast/ffi/node_modules/ffi/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /opt/AVCast/ffi/node_modules/ffi/build/config.gypi
gyp verb config.gypi checking for gypi file: /opt/AVCast/ffi/node_modules/ffi/config.gypi
gyp verb common.gypi checking for gypi file: /opt/AVCast/ffi/node_modules/ffi/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/share/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/AVCast/ffi/node_modules/ffi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/include/nodejs/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
gyp info spawn args   '-Dnode_gyp_dir=/usr/share/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/opt/AVCast/ffi/node_modules/ffi',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture arm64
gyp verb node dev dir /usr/include/nodejs
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/opt/AVCast/ffi/node_modules/ffi/build'
  cc '-DNODE_GYP_MODULE_NAME=ffi' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DPIC' '-DFFI_BUILDING' '-DHAVE_CONFIG_H' '-DNDEBUG' -I/usr/include/nodejs/include/node -I/usr/include/nodejs/src -I/usr/include/nodejs/deps/uv/include -I/usr/include/nodejs/deps/v8/include -I../deps/libffi/include -I../deps/libffi/config/linux/arm64  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/ffi/deps/libffi/src/prep_cif.o.d.raw  -c -o Release/obj.target/ffi/deps/libffi/src/prep_cif.o ../deps/libffi/src/prep_cif.c
../deps/libffi/src/prep_cif.c:26:17: fatal error: ffi.h: No such file or directory
 #include <ffi.h>
                 ^
compilation terminated.
deps/libffi/ffi.target.mk:112: recipe for target 'Release/obj.target/ffi/deps/libffi/src/prep_cif.o' failed
make: *** [Release/obj.target/ffi/deps/libffi/src/prep_cif.o] Error 1
make: Leaving directory '/opt/AVCast/ffi/node_modules/ffi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.14.79+
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild" "--verbose"
gyp ERR! cwd /opt/AVCast/ffi/node_modules/ffi
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

the config 'linux/arm64' doesn't exist in libffi
(I../deps/libffi/config/linux/arm64 doesn't exist)

we need a libffi upgrade

**Comment by mpo22** [comment]
on d3m3vilurr:feature/upgrade-libffi branch

root@avcast-odroidc2:/opt/AVCast/node-ffi.mpo22# node-gyp rebuild --verbose
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/nodejs', '/usr/bin/node-gyp', 'rebuild', '--verbose' ]
gyp info using node-gyp@3.4.0
gyp info using node@4.6.1 | linux | arm64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.12+\n"
gyp verb get node dir no --target version specified, falling back to host node version: 4.6.1
gyp verb build dir attempting to create "build" dir: /opt/AVCast/node-ffi.mpo22/build
gyp verb build dir "build" dir needed to be created? /opt/AVCast/node-ffi.mpo22/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /opt/AVCast/node-ffi.mpo22/build/config.gypi
gyp verb config.gypi checking for gypi file: /opt/AVCast/node-ffi.mpo22/config.gypi
gyp verb common.gypi checking for gypi file: /opt/AVCast/node-ffi.mpo22/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/share/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/AVCast/node-ffi.mpo22/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/include/nodejs/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
gyp info spawn args   '-Dnode_gyp_dir=/usr/share/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/opt/AVCast/node-ffi.mpo22',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture arm64
gyp verb node dev dir /usr/include/nodejs
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/opt/AVCast/node-ffi.mpo22/build'
  cc '-DNODE_GYP_MODULE_NAME=ffi' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DPIC' '-DFFI_BUILDING' '-DHAVE_CONFIG_H' '-DNDEBUG' -I/usr/include/nodejs/include/node -I/usr/include/nodejs/src -I/usr/include/nodejs/deps/uv/include -I/usr/include/nodejs/deps/v8/include -I../deps/libffi/include -I../deps/libffi  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/ffi/deps/libffi/src/prep_cif.o.d.raw  -c -o Release/obj.target/ffi/deps/libffi/src/prep_cif.o ../deps/libffi/src/prep_cif.c
  cc '-DNODE_GYP_MODULE_NAME=ffi' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DPIC' '-DFFI_BUILDING' '-DHAVE_CONFIG_H' '-DNDEBUG' -I/usr/include/nodejs/include/node -I/usr/include/nodejs/src -I/usr/include/nodejs/deps/uv/include -I/usr/include/nodejs/deps/v8/include -I../deps/libffi/include -I../deps/libffi  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/ffi/deps/libffi/src/types.o.d.raw  -c -o Release/obj.target/ffi/deps/libffi/src/types.o ../deps/libffi/src/types.c
  cc '-DNODE_GYP_MODULE_NAME=ffi' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DPIC' '-DFFI_BUILDING' '-DHAVE_CONFIG_H' '-DNDEBUG' -I/usr/include/nodejs/include/node -I/usr/include/nodejs/src -I/usr/include/nodejs/deps/uv/include -I/usr/include/nodejs/deps/v8/include -I../deps/libffi/include -I../deps/libffi  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/ffi/deps/libffi/src/raw_api.o.d.raw  -c -o Release/obj.target/ffi/deps/libffi/src/raw_api.o ../deps/libffi/src/raw_api.c
  cc '-DNODE_GYP_MODULE_NAME=ffi' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DPIC' '-DFFI_BUILDING' '-DHAVE_CONFIG_H' '-DNDEBUG' -I/usr/include/nodejs/include/node -I/usr/include/nodejs/src -I/usr/include/nodejs/deps/uv/include -I/usr/include/nodejs/deps/v8/include -I../deps/libffi/include -I../deps/libffi  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/ffi/deps/libffi/src/java_raw_api.o.d.raw  -c -o Release/obj.target/ffi/deps/libffi/src/java_raw_api.o ../deps/libffi/src/java_raw_api.c
  cc '-DNODE_GYP_MODULE_NAME=ffi' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DPIC' '-DFFI_BUILDING' '-DHAVE_CONFIG_H' '-DNDEBUG' -I/usr/include/nodejs/include/node -I/usr/include/nodejs/src -I/usr/include/nodejs/deps/uv/include -I/usr/include/nodejs/deps/v8/include -I../deps/libffi/include -I../deps/libffi  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/ffi/deps/libffi/src/closures.o.d.raw  -c -o Release/obj.target/ffi/deps/libffi/src/closures.o ../deps/libffi/src/closures.c
  cc '-DNODE_GYP_MODULE_NAME=ffi' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DPIC' '-DFFI_BUILDING' '-DHAVE_CONFIG_H' '-DNDEBUG' -I/usr/include/nodejs/include/node -I/usr/include/nodejs/src -I/usr/include/nodejs/deps/uv/include -I/usr/include/nodejs/deps/v8/include -I../deps/libffi/include -I../deps/libffi  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/ffi/deps/libffi/src/aarch64/sysv.o.d.raw  -c -o Release/obj.target/ffi/deps/libffi/src/aarch64/sysv.o ../deps/libffi/src/aarch64/sysv.S
  cc '-DNODE_GYP_MODULE_NAME=ffi' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DPIC' '-DFFI_BUILDING' '-DHAVE_CONFIG_H' '-DNDEBUG' -I/usr/include/nodejs/include/node -I/usr/include/nodejs/src -I/usr/include/nodejs/deps/uv/include -I/usr/include/nodejs/deps/v8/include -I../deps/libffi/include -I../deps/libffi  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/ffi/deps/libffi/src/aarch64/ffi.o.d.raw  -c -o Release/obj.target/ffi/deps/libffi/src/aarch64/ffi.o ../deps/libffi/src/aarch64/ffi.c
../deps/libffi/src/aarch64/ffi.c: In function ‘copy_hfa_to_reg_or_stack’:
../deps/libffi/src/aarch64/ffi.c:577:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (i = 0; i < elems; i++)
                     ^
../deps/libffi/src/aarch64/ffi.c: In function ‘aarch64_prep_args’:
../deps/libffi/src/aarch64/ffi.c:666:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (i = 0; i < ecif->cif->nargs; i++)
                 ^
../deps/libffi/src/aarch64/ffi.c:718:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
        for (j = 0; j < (ty->size + 7) / 8; j++)
                      ^
../deps/libffi/src/aarch64/ffi.c: In function ‘ffi_prep_cif_machdep’:
../deps/libffi/src/aarch64/ffi.c:777:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (i = 0; i < cif->nargs; i++)
                     ^
../deps/libffi/src/aarch64/ffi.c: In function ‘ffi_call’:
../deps/libffi/src/aarch64/ffi.c:869:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (j = 0; j < elems; j++)
                     ^
../deps/libffi/src/aarch64/ffi.c: In function ‘ffi_closure_SYSV_inner’:
../deps/libffi/src/aarch64/ffi.c:975:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (i = 0; i < cif->nargs; i++)
                 ^
../deps/libffi/src/aarch64/ffi.c:1032:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    for (j = 0; j < element_count (ty); j++)
                  ^
../deps/libffi/src/aarch64/ffi.c:1053:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    for (j = 0; j < element_count (ty); j++)
                  ^
../deps/libffi/src/aarch64/ffi.c:1151:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
        for (j = 0; j < elems; j++)
                      ^
  rm -f Release/obj.target/deps/libffi/libffi.a && ar crs Release/obj.target/deps/libffi/libffi.a Release/obj.target/ffi/deps/libffi/src/prep_cif.o Release/obj.target/ffi/deps/libffi/src/types.o Release/obj.target/ffi/deps/libffi/src/raw_api.o Release/obj.target/ffi/deps/libffi/src/java_raw_api.o Release/obj.target/ffi/deps/libffi/src/closures.o Release/obj.target/ffi/deps/libffi/src/aarch64/sysv.o Release/obj.target/ffi/deps/libffi/src/aarch64/ffi.o
  ln -f "Release/obj.target/deps/libffi/libffi.a" "Release/libffi.a" 2>/dev/null || (rm -rf "Release/libffi.a" && cp -af "Release/obj.target/deps/libffi/libffi.a" "Release/libffi.a")
  g++ '-DNODE_GYP_MODULE_NAME=ffi_bindings' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/usr/include/nodejs/include/node -I/usr/include/nodejs/src -I/usr/include/nodejs/deps/uv/include -I/usr/include/nodejs/deps/v8/include -I../node_modules/nan -I../deps/libffi/include -I../deps/libffi  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF ./Release/.deps/Release/obj.target/ffi_bindings/src/ffi.o.d.raw   -c -o Release/obj.target/ffi_bindings/src/ffi.o ../src/ffi.cc
../src/ffi.cc: In static member function ‘static void FFI::InitializeBindings(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/ffi.cc:73:18: error: ‘FFI_UNIX64’ was not declared in this scope
   SET_ENUM_VALUE(FFI_UNIX64);
                  ^
../src/ffi.cc:32:31: note: in definition of macro ‘SET_ENUM_VALUE’
   Nan::New<Integer>((uint32_t)_value), \
                               ^~~~~~
ffi_bindings.target.mk:103: recipe for target 'Release/obj.target/ffi_bindings/src/ffi.o' failed
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
make: Leaving directory '/opt/AVCast/node-ffi.mpo22/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.14.79+
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild" "--verbose"
gyp ERR! cwd /opt/AVCast/node-ffi.mpo22
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
ro

**Comment by mpo22** [comment]
fixed on commit
https://github.com/mpo22/node-ffi/commit/b9938b7e5e9dc9acf68d6bfc0f6ef0eee6414227
